title = "Treylon Wofford"

languageCode = "en"
languageName = "English"
weight = 1

[languages]
[languages.en]
htmlCode = "en"
displayName = "EN"
rtl = false


[params.author]
name = "Treylon Wofford"
image = "img/avatar.jpg"
headline = "IAM Engineer"
links = [
  { youtube = "https://www.youtube.com/@museNetcreations" },
  { github = "https://github.com/james-millner" },
  { linkedin = "https://www.linkedin.com/in/treylon-wofford/" },
#  { email = "treylonwofford2@gmail.com" }
]

