title = "Treylon Wofford"

languageCode = "en"
languageName = "English"
weight = 1

[languages]
[languages.en]
htmlCode = "en"
displayName = "EN"
rtl = false


[params.author]
name = "Treylon Wofford"
image = "img/black_cat_nft_art.png"
headline = "Interpretability Researcher & IBM Qiskit Advocate"
links = [
  { youtube = "http://www.youtube.com/@alginai" },
  { github = "https://github.com/treylonwofford" },
  { linkedin = "https://www.linkedin.com/in/treylon-wofford/" },
#  { email = "treylonwofford2@gmail.com" }
]

